package policycenter;
// Generated by Selenium IDE

import environment.EnvironmentManager;
import environment.RunEnvironment;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import policycenter.pages.PCLoginPage;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class AccountSearchTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() throws IOException {
        EnvironmentManager.initWebDriver();
        driver = RunEnvironment.getWebDriver();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void test_accountSearch() throws InterruptedException {
        PCLoginPage pcLoginPage = new PCLoginPage(driver);
        pcLoginPage.setByXPathUsername("su");
        pcLoginPage.setByXPathPassword("gw");
        pcLoginPage.byXPathClickLogin();
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[@id=\'TabBar-AccountTab\']/div/div[2]")));
        }
        //enter account number
        driver.findElement(By.xpath("//div[@id=\'TabBar-AccountTab\']/div[3]/div")).click();
        driver.findElement(By.xpath("//input[@name=\'TabBar-AccountTab-AccountTab_AccountNumberSearchItem\']")).sendKeys("N001958701");
        driver.findElement(By.xpath("//div[@id=\'TabBar-AccountTab-AccountTab_AccountNumberSearchItem_Button\']/span")).click();
        Thread.sleep(4000);
        //logout
        driver.findElement(By.xpath("//div[@id=\'gw-TabBarWidget--settings\']/div/span")).click();

    }
}

